import React from 'react';
import { PropTypes } from 'prop-types';

import OfferPopup from '../offer-popup/offer-popup.js';



class OfferItem extends React.Component {
    render() {
        var info = this.props.data;

        // Connect the offer to the correct modal generated by OfferPopup
        var target = "#offer-select" + info.id;
        return (
            <div className="card">
                <div className="card-body">
                    <h5 className="card-title">{info.offer}</h5>
                    <h6 className="card-subtitle mb-2 text-muted">Price: {info.price} ISK</h6>
                    <h6 className="card-text">Valid For: {info.validFor}</h6>
                    <button className="btn btn-primary mr-1 mb-1" data-toggle="modal" data-target={target}>Select pizzas</button>
                    
                    {/* Popup overlay to select pizzas */}
                    <OfferPopup offer={info.offer} id={info.id} />
                    
                </div>
            </div>

        )
    }
}


OfferItem.propTypes = {
    data: PropTypes.shape({
        id: PropTypes.number, 
        offer: PropTypes.string, 
        price: PropTypes.number,
        validFor: PropTypes.string
    }).isRequired
}

export default OfferItem